
class GLOBAL():

    def __init__(self, CONT_ID_FILE, CONST_BLOCK_SIZE, FILE_ALLOCATION_TABLE, BIT_MAP_TABLE):
        self.CONT_ID_FILE = CONT_ID_FILE
        self.CONST_BLOCK_SIZE = CONST_BLOCK_SIZE
        self.FILE_ALLOCATION_TABLE = FILE_ALLOCATION_TABLE
        self.BIT_MAP_TABLE = BIT_MAP_TABLE

